/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * E-commerce shop API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface SuccessResponse {
  success: boolean;
  message?: string;
}

export interface Customer {
  id: number;
  phone: string;
  name?: string | null;
  avatarUrl?: string | null;
  language?: string | null;
  telegramId?: string | null;
  savedAddress?: string | null;
  createdAt: string;
}

export interface CustomerSearchBody {
  phone: string;
}

export interface CustomerSearchResult {
  exists: boolean;
  customer?: Customer | null;
}

export interface CustomerLoginBody {
  phone: string;
  name?: string;
}

export interface UpdateProfileBody {
  name?: string;
  avatarUrl?: string;
  language?: string;
}

export type ProductUnit = (typeof ProductUnit)[keyof typeof ProductUnit];

export const ProductUnit = {
  dona: "dona",
  kg: "kg",
  pachka: "pachka",
} as const;

export interface Product {
  id: number;
  name: string;
  description?: string | null;
  price: number;
  oldPrice?: number | null;
  images: string[];
  categoryId?: number | null;
  categoryName?: string | null;
  inStock: boolean;
  unit: ProductUnit;
  isLiked: boolean;
  createdAt: string;
}

export interface ProductsListResponse {
  products: Product[];
  total: number;
  page: number;
  limit: number;
}

export type CreateProductBodyUnit =
  (typeof CreateProductBodyUnit)[keyof typeof CreateProductBodyUnit];

export const CreateProductBodyUnit = {
  dona: "dona",
  kg: "kg",
  pachka: "pachka",
} as const;

export interface CreateProductBody {
  name: string;
  description?: string;
  price: number;
  oldPrice?: number;
  images: string[];
  categoryId?: number;
  inStock?: boolean;
  unit?: CreateProductBodyUnit;
}

export type UpdateProductBodyUnit =
  (typeof UpdateProductBodyUnit)[keyof typeof UpdateProductBodyUnit];

export const UpdateProductBodyUnit = {
  dona: "dona",
  kg: "kg",
  pachka: "pachka",
} as const;

export interface UpdateProductBody {
  name?: string;
  description?: string;
  price?: number;
  oldPrice?: number;
  images?: string[];
  categoryId?: number;
  inStock?: boolean;
  unit?: UpdateProductBodyUnit;
}

export interface Category {
  id: number;
  name: string;
  imageUrl?: string | null;
  productCount: number;
}

export interface CreateCategoryBody {
  name: string;
  imageUrl?: string;
}

export interface CartItem {
  id: number;
  productId: number;
  quantity: number;
  product: Product;
}

export interface AddToCartBody {
  productId: number;
  quantity?: number;
}

export interface UpdateCartItemBody {
  quantity: number;
}

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export const OrderStatus = {
  new: "new",
  preparing: "preparing",
  delivered: "delivered",
  cancelled: "cancelled",
} as const;

export type OrderDeliveryMethod =
  (typeof OrderDeliveryMethod)[keyof typeof OrderDeliveryMethod];

export const OrderDeliveryMethod = {
  delivery: "delivery",
  pickup: "pickup",
} as const;

export type OrderPaymentMethod =
  (typeof OrderPaymentMethod)[keyof typeof OrderPaymentMethod];

export const OrderPaymentMethod = {
  cash: "cash",
  card: "card",
  online: "online",
} as const;

export interface OrderItem {
  id: number;
  productId: number;
  productName: string;
  productImage?: string | null;
  quantity: number;
  price: number;
}

export interface Order {
  id: number;
  customerId: number;
  customerName?: string | null;
  customerPhone?: string | null;
  courierId?: number | null;
  courierName?: string | null;
  courierPhone?: string | null;
  courierLat?: number | null;
  courierLng?: number | null;
  status: OrderStatus;
  deliveryMethod: OrderDeliveryMethod;
  paymentMethod: OrderPaymentMethod;
  address?: string | null;
  note?: string | null;
  promoCode?: string | null;
  discountAmount: number;
  totalPrice: number;
  deliveryFee: number;
  items: OrderItem[];
  createdAt: string;
}

export interface Courier {
  id: number;
  name: string;
  phone: string;
  username: string;
  isActive: boolean;
  lat?: number | null;
  lng?: number | null;
  locationUpdatedAt?: string | null;
  createdAt: string;
}

export interface CreateCourierBody {
  name: string;
  phone: string;
  username: string;
  password: string;
  isActive?: boolean;
}

export interface UpdateCourierBody {
  name?: string;
  phone?: string;
  username?: string;
  password?: string;
  isActive?: boolean;
}

export interface CourierLoginBody {
  username: string;
  password: string;
}

export interface CourierLoginResponse {
  id: number;
  name: string;
  phone: string;
  username: string;
}

export interface UpdateCourierLocationBody {
  lat: number;
  lng: number;
}

export interface AssignCourierBody {
  courierId?: number | null;
}

export type CreateOrderBodyDeliveryMethod =
  (typeof CreateOrderBodyDeliveryMethod)[keyof typeof CreateOrderBodyDeliveryMethod];

export const CreateOrderBodyDeliveryMethod = {
  delivery: "delivery",
  pickup: "pickup",
} as const;

export type CreateOrderBodyPaymentMethod =
  (typeof CreateOrderBodyPaymentMethod)[keyof typeof CreateOrderBodyPaymentMethod];

export const CreateOrderBodyPaymentMethod = {
  cash: "cash",
  card: "card",
  online: "online",
} as const;

export interface CreateOrderBody {
  deliveryMethod: CreateOrderBodyDeliveryMethod;
  paymentMethod: CreateOrderBodyPaymentMethod;
  address?: string;
  note?: string;
  promoCode?: string;
}

export type PromoCodeDiscountType =
  (typeof PromoCodeDiscountType)[keyof typeof PromoCodeDiscountType];

export const PromoCodeDiscountType = {
  fixed: "fixed",
  percent: "percent",
} as const;

export interface PromoCode {
  id: number;
  code: string;
  discountType: PromoCodeDiscountType;
  discountAmount: number;
  maxUses?: number | null;
  usedCount: number;
  isActive: boolean;
  createdAt: string;
}

export type CreatePromoCodeBodyDiscountType =
  (typeof CreatePromoCodeBodyDiscountType)[keyof typeof CreatePromoCodeBodyDiscountType];

export const CreatePromoCodeBodyDiscountType = {
  fixed: "fixed",
  percent: "percent",
} as const;

export interface CreatePromoCodeBody {
  code: string;
  discountType: CreatePromoCodeBodyDiscountType;
  discountAmount: number;
  maxUses?: number;
  isActive?: boolean;
}

export type UpdatePromoCodeBodyDiscountType =
  (typeof UpdatePromoCodeBodyDiscountType)[keyof typeof UpdatePromoCodeBodyDiscountType];

export const UpdatePromoCodeBodyDiscountType = {
  fixed: "fixed",
  percent: "percent",
} as const;

export interface UpdatePromoCodeBody {
  code?: string;
  discountType?: UpdatePromoCodeBodyDiscountType;
  discountAmount?: number;
  maxUses?: number;
  isActive?: boolean;
}

export interface ApplyPromoCodeBody {
  code: string;
  subtotal: number;
}

export interface ApplyPromoCodeResponse {
  discountAmount: number;
  promoCode: string;
  discountType: string;
  discountPercent?: number | null;
}

export interface Notification {
  id: number;
  message: string;
  createdAt: string;
}

export type UpdateOrderStatusBodyStatus =
  (typeof UpdateOrderStatusBodyStatus)[keyof typeof UpdateOrderStatusBodyStatus];

export const UpdateOrderStatusBodyStatus = {
  new: "new",
  preparing: "preparing",
  delivered: "delivered",
  cancelled: "cancelled",
} as const;

export interface UpdateOrderStatusBody {
  status: UpdateOrderStatusBodyStatus;
}

export interface ToggleLikeBody {
  productId: number;
}

export interface LikeResponse {
  liked: boolean;
}

export type MessageSenderType =
  (typeof MessageSenderType)[keyof typeof MessageSenderType];

export const MessageSenderType = {
  customer: "customer",
  admin: "admin",
} as const;

export type MessageMediaType =
  | (typeof MessageMediaType)[keyof typeof MessageMediaType]
  | null;

export const MessageMediaType = {
  image: "image",
  video: "video",
} as const;

export interface Message {
  id: number;
  customerId: number;
  senderType: MessageSenderType;
  text: string;
  mediaUrl?: string | null;
  mediaType?: MessageMediaType;
  isRead: boolean;
  createdAt: string;
}

export type SendMessageBodyMediaType =
  (typeof SendMessageBodyMediaType)[keyof typeof SendMessageBodyMediaType];

export const SendMessageBodyMediaType = {
  image: "image",
  video: "video",
} as const;

export type SendMessageBodySenderType =
  (typeof SendMessageBodySenderType)[keyof typeof SendMessageBodySenderType];

export const SendMessageBodySenderType = {
  customer: "customer",
  admin: "admin",
} as const;

export interface SendMessageBody {
  customerId?: number;
  text?: string;
  mediaUrl?: string;
  mediaType?: SendMessageBodyMediaType;
  senderType: SendMessageBodySenderType;
}

export type MarkReadBodySenderType =
  (typeof MarkReadBodySenderType)[keyof typeof MarkReadBodySenderType];

export const MarkReadBodySenderType = {
  customer: "customer",
  admin: "admin",
} as const;

export interface MarkReadBody {
  customerId: number;
  senderType: MarkReadBodySenderType;
}

export interface Banner {
  id: number;
  imageUrl: string;
  title?: string | null;
  link?: string | null;
  isActive: boolean;
  sortOrder: number;
  createdAt: string;
}

export interface CreateBannerBody {
  imageUrl: string;
  title?: string;
  link?: string;
  isActive?: boolean;
  sortOrder?: number;
}

export interface DeliverySettings {
  deliveryFee: number;
  freeDeliveryThreshold: number;
  estimatedMinutes: number;
}

export interface UpdateDeliveryBody {
  deliveryFee?: number;
  freeDeliveryThreshold?: number;
  estimatedMinutes?: number;
}

export interface SupportContact {
  phone: string;
  telegram?: string | null;
}

export interface UpdatePasswordBody {
  currentPassword: string;
  newPassword: string;
}

export interface AdminLoginBody {
  password: string;
}

export interface SendNotificationBody {
  message: string;
}

export interface DashboardStats {
  totalOrders: number;
  totalCustomers: number;
  totalRevenue: number;
  newOrders: number;
  preparingOrders: number;
  deliveredOrders: number;
  todayRevenue: number;
  todayOrders: number;
}

export interface OrderStatusCount {
  status: string;
  count: number;
}

export interface SiteSettings {
  siteName?: string | null;
  logoUrl?: string | null;
}

export type ListProductsParams = {
  categoryId?: number;
  search?: string;
  page?: number;
  limit?: number;
};

export type ListOrdersParams = {
  status?: ListOrdersStatus;
  customerId?: number;
};

export type ListOrdersStatus =
  (typeof ListOrdersStatus)[keyof typeof ListOrdersStatus];

export const ListOrdersStatus = {
  new: "new",
  preparing: "preparing",
  delivered: "delivered",
  cancelled: "cancelled",
} as const;

export type ListMessagesParams = {
  customerId?: number;
};

export type ClearMessagesParams = {
  customerId?: number;
};

export type TelegramWebhookBody = { [key: string]: unknown };
